# Generated by Django 5.1.5 on 2025-02-25 15:39

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='image_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='image_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='shoe',
            name='image_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='image_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='shoe',
            name='image_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shoe_images/'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='stock',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
